exercise2.settings:
  type: config_object
  label: 'Exercise2 - Paywall content settings'
  mapping:
    paywall_link:
      type: string
      label: 'Premium content registration link'
    paywall_notice:
      type: text
      label: 'Paywall content notice'
     